### ISSUE TITLE
Apply C11, C12, C13 pointing change and announce

### ISSUE THREAD

**Issue by mrtommyb** [KeplerGO/K2fov#13]
The roll for C11-C13 will change by the following amounts

C11: +0.16 deg
C12: +0.12 deg
C13: +0.16 deg

**Comment by mrtommyb** [comment]
I can do this. Is the only place that this needs changing in the file `K2fov/data/k2-campaign-parameters.json` ?

**Comment by barentsen** [comment]
Yes, `k2-campaign-parameters.json` is the only place where such things are defined now.  That is the file that needs to be edited.

As I understand it, the +0.12/+0.16 deg change is in the _solar roll angle_.  Do we know for sure that the change has the same magnitude and sign (!) in K2fov's definition of _roll_?  @fergalm

**Comment by barentsen** [comment]
I'm going to update this now following the assumption that we can just add +0.16/+0.12/+0.16 to the roll.  This will need to be double-checked once the corresponding KACRs are updated.

**Comment by barentsen** [comment]
Done.  I have bumped the version to `4.0.0` so that it is easy to tell people what version they need.

The blog post should mention that the version can be checked as follows:

```
python -c "import pkg_resources; print(pkg_resources.require('K2fov')[0].version)"
```

**Comment by mrtommyb** [comment]
with your new version i guess we can check the verion

``` bash
python -c 'from K2fov import version; print version.__version__'
```

**Comment by mrtommyb** [comment]
let's make a new release then I'll push to pypi

**Comment by mrtommyb** [comment]
I've pushed to pypi

**Comment by barentsen** [comment]
Blog post drafted, but could do with a proof read.  If not, will publish by noon.

https://github.com/KeplerGO/KeplerScienceWebsite/blob/master/content/news/Cycle4-roll-change.md
