### ISSUE TITLE
Get a DOI and ADS entry for `K2fov` 

### ISSUE THREAD

**Issue by barentsen** [KeplerGO/K2fov#7]
When we are done with the current revisions, we should register this code with Zenodo and then the Astrophysics Source Code Library (ASCL).  This would make it citable and give it an ADS entry, respectively.

I guess the author list should be: "Mullally, Barclay, Barentsen"?
@fergalm @mrtommyb is this OK?

**Comment by mrtommyb** [comment]
this is the correct author list

**Comment by fergalm** [comment]
That looks right to me. Do we need some kind of published article to get onto ASCL or is that optional?

**Comment by barentsen** [comment]
It needs to be ~associated with literature, but we should be able to get someone to mention and cite it easily enough, unless you wanted to write a paper?

**Comment by fergalm** [comment]
I really really really want to write a paper on it. Please yes.
I just checked http://ascl.net/code/submit  A literature reference is not required.

**Comment by barentsen** [comment]
We have a bibcode for K2fov now!  It is `2016ascl.soft01009M` and should appear on ADS in a few days.

cf. http://ascl.net/1601.009

**Comment by barentsen** [comment]
(The C9 white paper will cite K2fov, which enabled this.)
